services:
  db:
    image: postgres
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  # Redis:https://github.com/redis/ioredis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts-all-app-backend
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: npm run dev
    expose:
      - 80
      - 9229
    ports:
      - 3000:80
      - 9229:9229
    depends_on:
      - db
      - redis

volumes:
  db-data:
