services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ts-all-app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Redis:https://github.com/redis/ioredis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts-all-app-backend
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: npm run dev
    expose:
      - 80
      - 9229
    ports:
      - 3000:80
      - 9229:9229
    depends_on:
      - db
      - redis

volumes:
  db-data:
